# Generated by Django 5.0.4 on 2024-07-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_photocomment_user_photolike_user'),
        ('photos', '0006_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='photos.photo'),
        ),
    ]
